//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollOff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rolloff
    {
        public string Country { get; set; }
        public Nullable<double> Global_Group_ID { get; set; }
        public double Employee_no { get; set; }
        public string Name { get; set; }
        public string Local_Grade { get; set; }
        public string Main_Client { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public Nullable<double> Project_Code { get; set; }
        public string Project_Name { get; set; }
        public Nullable<System.DateTime> Project_Start_Date { get; set; }
        public Nullable<System.DateTime> Project_End_Date { get; set; }
        public string People_Manager__Performance_Reviewer_ { get; set; }
        public string Practice { get; set; }
        public string PSP_Name { get; set; }
        public string New_Global_Practice { get; set; }
        public string Office_City { get; set; }
    }
}
